### ISSUE TITLE
OSX hdf5 make error

### ISSUE THREAD

**Issue by adangert** [tbeu/matio#94] opened 2018-10-11 01:18 UTC
I get this error when running the make command, I have hdf5 installed via brew:

```
main-10-230-5-186:matio-1.5.2 aaron$ make
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I.    -g -O2 -c -o mat73.lo mat73.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -g -O2 -c mat73.c  -fno-common -DPIC -o .libs/mat73.o
mat73.c:599:69: error: too few arguments to function call, expected 4, have 3
                ref_id = H5Rdereference(dset_id,H5R_OBJECT,ref_ids+i);
                         ~~~~~~~~~~~~~~                             ^
/usr/local/include/H5Rpublic.h:80:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
       ^
mat73.c:904:58: error: too few arguments to function call, expected 4, have 3
                                                ref_ids+l);
                                                         ^
/usr/local/include/H5Rpublic.h:80:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
       ^
mat73.c:1033:73: error: too few arguments to function call, expected 4, have 3
                    ref_id = H5Rdereference(dset_id,H5R_OBJECT,ref_ids+i);
                             ~~~~~~~~~~~~~~                             ^
/usr/local/include/H5Rpublic.h:80:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
       ^
mat73.c:2788:77: error: too few arguments to function call, expected 4, have 3
                        ref_id = H5Rdereference(dset_id,H5R_OBJECT,ref_ids+i);
                                 ~~~~~~~~~~~~~~                             ^
/usr/local/include/H5Rpublic.h:80:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
       ^
4 errors generated.
make[2]: *** [mat73.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by tbeu** [comment] 2018-10-11 06:28
Why matio v1.5.2 then?

**Comment by tbeu** [comment] 2018-10-11 06:40
Duplicate of #37.

**Closed by tbeu** 2018-10-11 06:40 UTC
Labels: duplicate
