### ISSUE TITLE
Mat_VarReadNextInfoIterate takes a long time to read mat-file

### ISSUE THREAD

**Issue by GolubevaP** [tbeu/matio#196] opened 2022-12-13 09:28 UTC
Reading the header by indexes takes a lot of time (several minutes), moreover, it requires a lot of memory to read it. Although this is only needed to make sure that the file can be opened.
I realized that the problem is in this method (Mat_VarReadNextInfoIterate), in particular, in nested loops. And also this problem met earlier (https://github.com/tbeu/matio/issues/157). Will you fix it?

**Comment by Ri0n** [comment] 2023-01-13 08:55
Hello dear developers.

This PR https://github.com/tbeu/matio/pull/197 partially resolves the problem.
But the root of the problem is hidden in usage of `H5Iget_name` which is extremely slow.

**Comment by Ri0n** [comment] 2023-01-13 09:31
And there is a PR for avoiding usage of H5Iget_name
https://github.com/Ri0n/matio/pull/1/files

**Comment by Ri0n** [comment] 2023-01-13 09:51
A PR for `H5Iget_name` against this repo https://github.com/tbeu/matio/pull/198
I'm very worried if I could break anything with this change. So I hope developers can propose appropriate tests and teest it on their own.

**Comment by tbeu** [comment] 2023-01-14 08:52
@Ri0n Thanks for both your PRs. They are very appreciated.

**Comment by tbeu** [comment] 2023-01-24 19:52
@GolubevaP Which MAT-file version did you use? Do you have any MAT-file to share? Thanks.

**Comment by tbeu** [comment] 2023-10-21 08:58
> @GolubevaP Which MAT-file version did you use? Do you have any MAT-file to share? Thanks.

@GolubevaP Since #157 is fixed and @Ri0n contributed his fixes, can you please test again. Thanks!

**Comment by tbeu** [comment] 2024-01-06 09:25
Closing after @GolubevaP not responding.

**Closed by tbeu** 2024-01-06 09:25 UTC
