### ISSUE TITLE
Performance when reading large .mat file with nested structs

### ISSUE THREAD

**Issue by aitorperezzz** [tbeu/matio#163] opened 2021-03-05 00:43 UTC
Hi, I am trying to read a large .mat file (approximately one gig) on Linux and I am seeing that accessing variables inside nested structs takes a long time (about 15 seconds when the nesting level is around 3). Is this to be expected? Is there any way to improve performance?

I can provide versions of the library, compiler, os and general environment if needed.

**Comment by tbeu** [comment] 2021-03-06 09:12
See also #55 and #140. I am afraid it is the best we can achieve currently.

Can you run

```sh
/usr/bin/time -f "%es %MK" ./tools/matdump file.mat > log1.txt
/usr/bin/time -f "%es %MK" ./tools/matdump -d file.mat > log2.txt
````

and provide the stdout. If you have a simple m script to create such a MAT file in MATLAB I would be interested, too.

I also created https://github.com/tbeu/matioPerformance (on Win OS only) to compare MAT file reading, but it is not up to date regarding libmatio.dll.

**Comment by tbeu** [comment] 2021-03-19 06:40
Closing as duplicate of #65.

**Closed by tbeu** 2021-03-19 06:40 UTC
Labels: duplicate

**Comment by tbeu** [comment] 2023-10-21 09:57
@aitorperezzz FYI: https://github.com/tbeu/matioPerformance is updated to the upcoming libmatio v1.5.24.
