### ISSUE TITLE
My mat file version is v7.0. Can savemat set this version number?Thank you.

### ISSUE THREAD

**Issue by Qianzujin** [tbeu/matio#154] opened 2020-09-16 06:52 UTC
My mat file version is v7.0. Can savemat set this version number?Thank you.

**Comment by tbeu** [comment] 2020-09-16 15:52
How did you create it?

**Comment by Qianzujin** [comment] 2020-09-17 00:22
![-4ca7e7e8a28e8d7f.jpg](https://user-images.githubusercontent.com/49854479/93405101-a7264800-f8be-11ea-8519-f00c2733d2d5.jpg)
There are three options on the picture. I can only save the options above and below through the matio library. I can't save the options of version 7.0 in the middle. If you have any methods, please let me know. Thank you very much!

**Comment by tbeu** [comment] 2020-09-17 16:03
Duplicate of https://sourceforge.net/p/matio/discussion/609377/thread/28532fb664/#0605, but I agree, the versioning is confusing.

**Closed by tbeu** 2020-09-17 16:03 UTC

**Comment by Qianzujin** [comment] 2020-09-18 00:33
I have read the article and tried to compress the mat file when saving it. But the mat file generated by Matlab is not exactly the same, so there is no way for the matio library to generate the - V7 version of the mat file? There are other ways, I am not very clear, if there is a way, please tell me, thank you very much.

**Comment by Qianzujin** [comment] 2020-09-18 00:34
My English is not very good, is through the translation program translation, if I said is difficult to understand, I am very sorry about this...

**Comment by tbeu** [comment] 2020-09-18 15:07
Here is the table of matio create/write options along with the corrsponding MATLAB save options.

| Create file by Mat_CreateVer | Write variables by Mat_VarWrite | Corresponding MATLAB save options |
| -- | -- | -- |
| mat_file_ver = MAT_FT_MAT4 | compress = MAT_COMPRESSION_NONE | -v4 |
| mat_file_ver = MAT_FT_MAT5 | compress = MAT_COMPRESSION_NONE | -v6 |
| mat_file_ver = MAT_FT_MAT5 | compress = MAT_COMPRESSION_ZLIB | -v7 |
| mat_file_ver = MAT_FT_MAT73 | compress = MAT_COMPRESSION_NONE | -v7.3 -nocompression |
| mat_file_ver = MAT_FT_MAT73 | compress = MAT_COMPRESSION_ZLIB | -v7.3 |

**Comment by Qianzujin** [comment] 2020-09-19 01:44
Thank you very much for your detailed answers, but I have tried these saving options, and there are still some differences between MATLAB native mat files and them. I will think of other ways to solve the problem, thank you very much again!
